backend:
  name: git-gateway
  branch: master  # Replace with your default Git branch name if it's not 'main'

media_folder: "public/images/uploads"  # Folder where uploaded media will go
public_folder: "/images/uploads"

collections:
  - name: "blog"           # The name of the collection
    label: "Blog"          # Label in the CMS UI
    folder: "src/blogs"    # Folder to store blog posts (create this folder)
    create: true           # Allow users to create new posts
    slug: "{{slug}}"       # URL-friendly slug for posts
    fields:                # Fields for each blog post
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
